version: 2.1

jobs:
  build:
    docker:
        - image: circleci/html:latest
      steps:
        - checkout
        - run:
            name: Echo build project
            command:
              echo "New version 2.1"
              echo "Run with HTML tools"

workflows:
  version: 2.1
  build_now:
    jobs:
      - build